#!/usr/bin/python3
import random
import string
import array

print('Welcome to the password generator.')

# determine the length
length = int(input('\nHow long do you want the password to be?: '))
MAX_LEN = 20

# characters that will be used

lower = string.ascii_lowercase
upper = string.ascii_uppercase
number = string.digits
symbols = string.punctuation

# form array with characters
COMBINATION = upper + lower + number + symbols

# select randomly from each group
random_number = random.choice(number)
random_lower = random.choice(lower) 
random_upper = random.choice(upper)
random_symbols = random.choice(symbols)

# combine randoms
passwords = random_number + random_upper + random_lower + random_symbols

# length
for x in range(MAX_LEN - 4):
	passwords = passwords + random.choice(COMBINATION)
	password = array.array('u', passwords)
	random.shuffle(password)

# form password
combo = ""
for x in password:
	combo = combo + x

# print out password
print(password)

